//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ismatik.ENTİTY.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunBilgileri
    {
        public string UrunAdi { get; set; }
        public int UrunID { get; set; }
        public string İndirim { get; set; }
        public string Fiyat { get; set; }
        public string SiteAdi { get; set; }
        public Nullable<System.DateTime> ListelemeTarihi { get; set; }
        public string anahtarKelime { get; set; }
    }
}
